/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Notes Collaboration API
 * API for managing notes, users, collaborations, and password reset with OTP verification.
 * OpenAPI spec version: 1.0.0
 */

export type GetNotes200Item = {
  id?: number;
  title?: string;
  description?: string;
  createdBy?: number;
};
