/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Notes Collaboration API
 * API for managing notes, users, collaborations, and password reset with OTP verification.
 * OpenAPI spec version: 1.0.0
 */

export type InviteCollaborator200 = {
  /** ID of the created collaboration. */
  id?: number;
  /** ID of the user being invited to collaborate. */
  userId?: number;
  /** ID of the note that the collaboration is for. */
  noteId?: number;
};
