/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Notes Collaboration API
 * API for managing notes, users, collaborations, and password reset with OTP verification.
 * OpenAPI spec version: 1.0.0
 */
import type { User } from "./user";

export type LoginUser200 = {
  user?: User;
  token?: string;
};
