/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Notes Collaboration API
 * API for managing notes, users, collaborations, and password reset with OTP verification.
 * OpenAPI spec version: 1.0.0
 */
import type { User } from "./user";
import type { Collaboration } from "./collaboration";

export interface Note {
  id: number;
  title?: string;
  category?: string;
  description?: string;
  createdBy?: number;
  createdAt?: string;
  updatedAt?: string;
  CreatedBy?: User;
  /** @nullable */
  Collaborations?: Collaboration[] | null;
}
